"""Multi-channel notification service supporting FCM, Telegram, and LINE."""

import asyncio
from typing import Optional
import httpx
from loguru import logger
from app.core.config import get_settings


class NotificationService:
    def __init__(self):
        self.cfg = get_settings()

    async def send_signal_alert(
        self,
        symbol: str,
        timeframe: str,
        direction: str,
        message: str,
        confluence_score: int,
        entry: Optional[float] = None,
        sl: Optional[float] = None,
        tp: Optional[float] = None,
        rr: Optional[float] = None,
    ) -> dict[str, bool]:
        """Broadcast signal alert to all configured channels (FCM, Telegram, LINE)."""
        results = {}

        tg_success, line_success, fcm_success = await asyncio.gather(
            self._send_telegram(
                symbol=symbol,
                timeframe=timeframe,
                direction=direction,
                message=message,
                confluence=confluence_score,
                entry=entry,
                sl=sl,
                tp=tp,
                rr=rr,
            ),
            self._send_line(
                symbol=symbol,
                timeframe=timeframe,
                direction=direction,
                message=message,
                confluence=confluence_score,
            ),
            self._send_fcm(
                title=f"🚨 Apex Signal: {direction.upper()} {symbol} ({timeframe})",
                body=message,
                data={"symbol": symbol, "timeframe": timeframe, "direction": direction},
            ),
        )
        results["telegram"] = tg_success
        results["line"] = line_success
        results["fcm"] = fcm_success

        return results

    async def _send_telegram(
        self,
        symbol: str,
        timeframe: str,
        direction: str,
        message: str,
        confluence: int,
        entry: Optional[float] = None,
        sl: Optional[float] = None,
        tp: Optional[float] = None,
        rr: Optional[float] = None,
    ) -> bool:
        if not self.cfg.telegram_bot_token or not self.cfg.telegram_chat_id:
            return False

        icon = "🟢" if direction.lower() == "long" else "🔴" if direction.lower() == "short" else "⚠️"
        text_lines = [
            f"{icon} APEX TRADING SIGNAL",
            "━━━━━━━━━━━━━━━━━━",
            f"Symbol: {symbol} | TF: {timeframe}",
            f"Direction: {direction.upper()}",
            f"Confluence: {confluence}/100",
            "",
        ]

        if entry and sl and tp:
            text_lines.extend([
                f"📍 Entry: {entry}",
                f"🛑 Stop Loss: {sl}",
                f"🎯 Take Profit: {tp}",
                f"⚖️ R:R Ratio: {rr or 'N/A'}",
                "",
            ])

        text_lines.extend([
            "Analysis:",
            f"{message}",
            "",
            "⏱ Generated by Apex AI Trade Advisor",
        ])

        payload = {
            "chat_id": self.cfg.telegram_chat_id,
            "text": "\n".join(text_lines),
        }

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                url = f"https://api.telegram.org/bot{self.cfg.telegram_bot_token}/sendMessage"
                resp = await client.post(url, json=payload)
                return resp.status_code == 200
        except Exception as e:
            logger.error(f"Failed to send Telegram alert: {e}")
            return False

    async def _send_line(
        self,
        symbol: str,
        timeframe: str,
        direction: str,
        message: str,
        confluence: int,
    ) -> bool:
        if not self.cfg.line_notify_token:
            return False

        line_msg = f"\n[Apex Signal] {direction.upper()} {symbol} ({timeframe})\nConfluence: {confluence}/100\n\n{message}"
        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    "https://notify-api.line.me/api/notify",
                    headers={"Authorization": f"Bearer {self.cfg.line_notify_token}"},
                    data={"message": line_msg},
                )
                return resp.status_code == 200
        except Exception as e:
            logger.error(f"Failed to send LINE alert: {e}")
            return False

    async def _send_fcm(self, title: str, body: str, data: dict) -> bool:
        if not self.cfg.fcm_server_key:
            return False

        try:
            # Format payload for FCM with stringified data map
            str_data = {str(k): str(v) for k, v in data.items()}
            payload = {
                "to": "/topics/signals",
                "notification": {"title": title, "body": body},
                "data": str_data,
            }
            async with httpx.AsyncClient(timeout=10.0) as client:
                resp = await client.post(
                    "https://fcm.googleapis.com/fcm/send",
                    headers={"Authorization": f"key={self.cfg.fcm_server_key.strip()}"},
                    json=payload,
                )
                if resp.status_code != 200:
                    logger.warning(f"[FCM] Push response status {resp.status_code}: {resp.text}")
                return resp.status_code == 200
        except Exception as e:
            logger.error(f"[FCM] Failed to send push: {e}")
            return False
